file.directory=files
spring.application.name=job4j_url_shortcut
spring.datasource.url=jdbc:postgresql://127.0.0.1:5432/shortcut
spring.datasource.username=postgres
spring.datasource.password=password
spring.datasource.driver-class-name=org.postgresql.Driver

spring.liquibase.url=jdbc:postgresql://127.0.0.1:5432/shortcut
spring.liquibase.user=postgres
spring.liquibase.password=password
spring.liquibase.change-log=classpath:db/dbchangelog.xml

springdoc.swagger-ui.tryItOutEnabled=true

jwt.token.secret = easehjkopyJhbGciOiJIUzI1NiJ9eyJzdWIiOiJzdHVkZW50X2pvYjRqIiwiaWF0Ijox
jwt.token.expired=3600000
